steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    
  # Step 2: Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'app'
      - 'deploy'
      - 'app.yaml'
      - '--quiet'
      - '--project=gen-lang-client-0566346208'
      - '--version=auto'

timeout: '1600s'

options:
  logging: CLOUD_LOGGING_ONLY
